version: 0.2
proxy:
    upload-artifacts: yes
    logs: yes
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=878291833136.dkr.ecr.ap-south-1.amazonaws.com/iaac
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH}
      - echo $REPOSITORY_URI:$IMAGE_TAG
  build:
    commands:
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - 'sed -i "s/repository:.*/repository: $REPOSITORY_URI/g" wordpress/values.yaml'
      - 'sed -i "s/repository:.*/repository: $REPOSITORY_URI/g" wordpress/values.yaml'
      - tar -cf wordpress 
      - mv wordpress wordpress-$IMAGE_TAG
      - aws s3 cp wordpress-$IMAGE_TAG.tar s3://codepipeline-ap-south-1-39504705325/wordpress-pipeline     
      - echo creating zip of helm chart
