apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wordpress.fullname" . }}-env
data:
  DB_USER: {{ .Values.configmap.dbUser }}
  DB_PASSWORD: {{ .Values.configmap.dbPassword }}
  DB_NAME: {{ .Values.configmap.dbName }}
  DB_HOST: {{ .Values.configmap.dbHost }}
